#!/bin/sh
printenv

echo ###############################################
echo Run with:
echo "      " cd `pwd`
echo "      " `printenv GPHL_INSTALLATION`/aP_wf_process "$@"
echo ###############################################

echo " NORMAL Termination"
